### ISSUE TITLE
Weather icons not display

### ISSUE THREAD

**Issue by echosmart792** [zagortenay333/conky-Vision#14] opened 2017-08-06 06:54 UTC
Hi !

For five mounth im not using Ubuntu, but i'm retourn on old love.
First step after installing OS it's this conky, but i have a little problem.
Icons not appear on screen.
This is terminal:
conky -c ~/.conkyrc 
conky: desktop window (2a0000a) is subwindow of root window (b4)
conky: window type - dock
conky: drawing to created window (0xc00002)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: unknown variable '$image'
conky: forked to background, pid is 20326

And this is print screen: imgur.com/a/bxArb

How it's possible to solve this ?
Thanks in advance !

**Comment by zagortenay333** [comment] 2017-08-06 08:55
Duplicate of #7

**Closed by zagortenay333** 2017-08-06 08:55 UTC
